name: Enforce CHANGELOG Update
on:
  pull_request:
    branches:
    - master
jobs:
  check-changelog-update:
    uses: membraneframework/membrane_core/.github/workflows/enforce-changelog-update.yml@action-enforcing-changelog-update
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}